services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - ./db/seed:/docker-entrypoint-initdb.d
  app:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: .
    container_name: brewers-diary-app
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=$SPRING_JPA_HIBERNATE_DDL_AUTO
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
networks:
  db:
    driver: bridge

volumes:
  db: