services:
  mongo_db:
    image: mongo:6-jammy
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_NON_ROOT_USERNAME=$MONGODB_USER
      - MONGO_NON_ROOT_PASSWORD=secret=$MONGODB_USER
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
      - ./scripts/db:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - mongo_db
    build: 
      context: ./app
      dockerfile: Dockerfile
      target: $SPRING_APP_ENV
    container_name: brewers-diary-app
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: